### ISSUE TITLE
camera moves automaticly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Izhido/qrevpak#12]
```
I tested with different GC controllers, and everytime I play quakerev or 
quake2rev the camera moves to the left automaticly so you can never stand 
still.I load both games from my 4GB SDcard in the homebrew channel, with the 
official .PAK files.
```

Original issue reported on code.google.com by `FragA...@gmail.com` on 25 Mar 2010 at 12:56

**Comment by Izhido** [comment]
Work on this project has been suspended. I don't currently have the means to develop or maintain it anymore, be either hardware or the knowledge of the current Wii dev tools. My deepest apologies for all inconveniences caused by this decision.
