### ISSUE TITLE
Button z doesn't work (Gamecube controller)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Izhido/qrevpak#15]
```
During gameplay button z is used to crouch, it doesn't work, no matter how the 
buttons are mapped, z button doesn't respond at all.

What version of the product are you using? On what operating system?
Release 1

Please provide any additional information below.
Using Wavebird GCN controller, original Nintendo brand.

```

Original issue reported on code.google.com by `s.barrer...@gmail.com` on 24 Jan 2012 at 6:30

**Comment by Izhido** [comment]
Work on this project has been suspended. I don't currently have the means to develop or maintain it anymore, be either hardware or the knowledge of the current Wii dev tools. My deepest apologies for all inconveniences caused by this decision.
