### ISSUE TITLE
Installation on SD

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Izhido/qrevpak#22]
```
Can you wrote a step-by-step tutorial?
I own the original CD-Rom of Quake I but what should I do now?

Cheers :-)

```

Original issue reported on code.google.com by `ene...@gmail.com` on 7 Apr 2012 at 9:19

**Comment by Izhido** [comment]
Work on this project has been suspended. I don't currently have the means to develop or maintain it anymore, be either hardware or the knowledge of the current Wii dev tools. My deepest apologies for all inconveniences caused by this decision.
