### ISSUE TITLE
quake 2 probelm with new release

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Izhido/qrevpak#24]
```
What steps will reproduce the problem?
1.beat the first boss and you will see bad pcx file pics/victory.pcx not found

2.and again nice work as always man! I like the new look with the gx engine 
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `blinxk2...@yahoo.com` on 20 May 2012 at 2:35

Attachments:
- [QRevPAK.err](https://storage.googleapis.com/google-code-attachments/qrevpak/issue-24/comment-0/QRevPAK.err)

**Comment by Izhido** [comment]
Work on this project has been suspended. I don't currently have the means to develop or maintain it anymore, be either hardware or the knowledge of the current Wii dev tools. My deepest apologies for all inconveniences caused by this decision.
