### ISSUE TITLE
Hardware mode to dark

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Izhido/qrevpak#25]
```
What steps will reproduce the problem?
1.Quake 2 in hardware GX mode
2.
3.

What is the expected output? What do you see instead?
Gamma level to dark

What version of the product are you using? On what operating system?
version 4

Please provide any additional information below.

Cannot change the gamma level in hardware GX mode - to dark. Running in  
software mode can change gamma level.
```

Original issue reported on code.google.com by `Robochu...@hotmail.com` on 22 May 2012 at 4:57

**Comment by Izhido** [comment]
Work on this project has been suspended. I don't currently have the means to develop or maintain it anymore, be either hardware or the knowledge of the current Wii dev tools. My deepest apologies for all inconveniences caused by this decision.
