### ISSUE TITLE
Sent back to homebrew channel

### ISSUE THREAD

**Issue by TDRRmk2** [Izhido/qrevpak#28]
Every time i open up Quake 2 or 1, everything will start loading, then the screen goes black, and fades back into the homebrew channel, what do i do?

**Comment by Izhido** [comment]
Unfortunately, there is only one answer I can give about the project right now.
I currently don't have the required hardware to develop or maintain it, as well as the knowledge of the status of the current toolchain or any Wii firmware able to run it. Meaning, there is nothing I can currently do about the issue you're talking about. My most sincere apologies for that.

**Comment by DongVGH** [comment]
Really? Thanks for answering, but i still wonder why it does run on other
Wii systems but on mine it doesn't.

2017-04-13 11:09 GMT-04:30 Izhido <notifications@github.com>:
